### ISSUE TITLE
Minimatch not matching file endings

### ISSUE THREAD

**Issue by appdevtk** [averrin/color-tabs-regex#10]
Hello,
I've setup some rules to color my tabs:
"_.js": "#ff0000"
"_.html": "#00ff00"
"_.md": "#0000ff"
"_.markdown": "#0000ff"
"_.html": "#ff00ff"
"_.css": "#00ffff"
"_.less": "#ff0082"
"_.json": "#ffff00"
"_.cson": "#fff491"
"_.coffee": "#ffa800"

And they are not matching. I'll create a pull request with my addition to fix this issue.

**Comment by bojidar-bg** [comment]
just write `"**.js"`, etc.

**Comment by bojidar-bg** [comment]
Close?

**Comment by averrin** [comment]
I merge, but not tested. But, if @appdevtk push it - i can close.
