### ISSUE TITLE
Uncaught TypeError: processPath is not a function

### ISSUE THREAD

**Issue by AndiDog** [averrin/color-tabs-regex#13]
I'm getting this error with Atom 1.1, probably some API change?

**Atom Version**: 1.1.0
**System**: Ubuntu 15.10
**Thrown From**: [color-tabs-regex](https://github.com/averrin/color-tabs-regex) package, v0.2.2
### Stack Trace

Uncaught TypeError: processPath is not a function

```
At /home/asommer/.atom/packages/color-tabs-regex/lib/color-tabs-regex.coffee:87

TypeError: processPath is not a function
  at /home/asommer/.atom/packages/color-tabs-regex/lib/color-tabs-regex.coffee:87:13
  at /opt/atom/resources/app.asar/node_modules/season/lib/cson.js:197:59
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by averrin** [comment]
Hi. thx got reporting, but can you write, how i can reproduce it?

**Comment by AndiDog** [comment]
I simply installed the latest package in Atom 1.1 and got the error. No detailed steps I could give you.

**Comment by averrin** [comment]
Ok, ill try it on 1.1.0 (i use beta channel, and it works)

**Comment by bojidar-bg** [comment]
@AndiDog have you installed the `color-tabs` package? This package depends on it..

**Comment by AndiDog** [comment]
Yes, that's it. Wasn't entirely clear to me because often Atom packages like this one are forks of the original project instead of additions...

Maybe the dependency can be declared in `package.json` (see https://discuss.atom.io/t/depending-on-other-packages/2360/23).
