### ISSUE TITLE
Tabs are not colored when moved between panes

### ISSUE THREAD

**Issue by kankaristo** [averrin/color-tabs-regex#16]
Tabs are left uncolored if you move a tab to another pane (or if you create a new pane).

I'm not really sure if this is an issue with color-tabs or with color-tabs-regex, because color-tabs-regex is the only way I use color-tabs.

**Comment by averrin** [comment]
Hi. Thx for reporting. I am not using this plugin, but i added onDidChangeActivePane handler. Not very good solution, but works sometimes ;)

**Comment by kankaristo** [comment]
That doesn't seem to fix it for me, but I figured out why.

I have "Break After First Match" turned on, which saves the **path** of any pane item that has already been colored. But multiple pane items can have the same path, since you can have the same file open in different tabs (in different panes or even in the same pane).

If you have the same file open in multiple panes, none of the copies get colored, but any file that is open in only one tab gets colored correctly. If "Break After First Match" is turned off, everything works as expected.

I figured out a way to fix this, I'll open a PR soon.

**Comment by kankaristo** [comment]
PR opened: https://github.com/averrin/color-tabs-regex/pull/17
