### ISSUE TITLE
Use something more user-frendly than regex

### ISSUE THREAD

**Issue by bojidar-bg** [averrin/color-tabs-regex#4]
It is much simpler to write rules using [minimatch](https://github.com/isaacs/minimatch) rather than regex. (Note that you can convert minimatch to regex if you think it is better...).

The best option will be to support both regex-based matching and minimatch/glob matching, but I can't wrap my head around it right now... :smile: 

I might try to make a PR out of it... one day...

**Comment by averrin** [comment]
Nice idea, i already see, that regex isnt friendly. I will smoke some documentation about atom packages and minimatch. PRs are welcome=)

**Comment by bojidar-bg** [comment]
BTW, should I submit more matching-related ideas? :smiley:

**Comment by averrin** [comment]
@bojidar-bg yeah. For now i prefer simple String.match, but i will implement all interesting ideas.
