### ISSUE TITLE
Implement "children" rules

### ISSUE THREAD

**Issue by bojidar-bg** [averrin/color-tabs-regex#5]
Currently my CSON file looks like:

``` CSON
"**/projectPath/subFolder/**/*.js" : "rgb(0,255,0)"
"**/projectPath/project.json" : "rgb(0,0,255)"
"**/projectPath/**/*.cfg" : "rgb(255,0,0)"
//...
```

It will be much cleaner if it was like:

``` CSON
"**/projectPath/":
    "subFolder/**/*.js" : "rgb(0,255,0)"
    "project.json" : "rgb(0,0,255)"
    "**/*.cfg" : "rgb(255,0,0)"
```

The easiest way to implement this I can think of is to concatenate the strings of the "parent" rule and the "child" rule.

(Note that rule inside rules inside rules inside rules should also be supported)

P.S. if you aren't as fast as the last time, I might make a PR :smiley:

**Comment by averrin** [comment]
Ok, but, plz, dont break support of String.match and basic "plain" rules.
For "projectPath" i suggest implement coffeescript templating: "#{projectPath}"

**Comment by bojidar-bg** [comment]
I think that it won't affect basic (regex) rules, because it will just concatenate strings.. And currently regexes are represented as Strings (see [this stackoverflow question](http://stackoverflow.com/questions/7365027/how-to-use-a-regexp-literal-as-object-key) for details), so it shouldn't be a problem.

And about the templating, I like the idea, though it need a separate issue :smile:... actually I meant some project path, cus I don't want to color the tabs of all my projects..

@averrin And again, thank you for making this great package :+1:¹⁰⁰

**Comment by bojidar-bg** [comment]
@averrin Ok, I made the PR :smiley:

**Comment by bojidar-bg** [comment]
Now... I guess it's time for a new tag? :smile:

**Comment by averrin** [comment]
Im not very good in coffeescript too, but after some magic it works=)
Need some more documentation in README (pr is welcome=))) ) and i will publish it

**Comment by bojidar-bg** [comment]
@averrin Ok, maybe a bit later I can make some docs for the new feature :smile:

**Comment by averrin** [comment]
@bojidar-bg sorry, i missed, that you are update readme already.

**Comment by averrin** [comment]
published

**Comment by bojidar-bg** [comment]
@averrin ~ Well, can you surround that sample code in ```` instead of ` ? (so it will be multiline)

**Comment by averrin** [comment]
I did it before publishing=)

**Comment by bojidar-bg** [comment]
LOL, didn't notice it ... xD

**Comment by bojidar-bg** [comment]
Nice.. I found a bug :smile: 
I can't have more than two levels of rules, e.g.

``` CSON
"**/Projects/":
  "nodejs/":
    "**/package.json": "red" # This won't ever make a match...
  "someProject/**/*.js": "green"
```

I think that if line 69 https://github.com/averrin/color-tabs-regex/blob/master/lib/color-tabs-regex.coffee#L69 is changed to 

```
        output = @expandRules(rules[rule], prefix + rule, output)
                                           ^^^^^^^^^ <- Added
```

this bug will not happen :smile:.

Sorry for sending such buggy code to you...

**Comment by bojidar-bg** [comment]
You repoened it just in order to close it? o.O

**Comment by averrin** [comment]
I confirmed this bug, and fix it.=)

**Comment by bojidar-bg** [comment]
=)
