### ISSUE TITLE
Add the "edit rules" option to the menu

### ISSUE THREAD

**Issue by bojidar-bg** [averrin/color-tabs-regex#7]
Two location I can think of are:
1. Edit->Open color-tabs-regex config file
2. Packages->Color Tabs Regex->Open config file

P.S. Sorry for "spamming" you with ideas :wink:

**Comment by bojidar-bg** [comment]
Should I continue spam, or are you too busy for this? :smile:

**Comment by averrin** [comment]
Plz, continue =) It was easy and i did it. If it will be more difficult - i leave comment. And will said "PRs are welcome" =)
