### ISSUE TITLE
coloring an unsaved tab is not supported

### ISSUE THREAD

**Issue by bojidar-bg** [averrin/color-tabs-regex#9]
A message box with this title pops up whenever I press ctrl-N :smile: (well, I still get a new file, so not a bug, just a warning)...

**Comment by averrin** [comment]
Its a logic of color-tabs service. Coloring based on path, but unsaved tab have no path. I think, its a correct behavior.

**Comment by bojidar-bg** [comment]
So... I should report it over there?

**Comment by averrin** [comment]
I dont think so:

```
processPath= (path,color,revert=false,save=false) ->
  unless path?
    atom.notifications.addWarning "coloring a unsaved tab is not supported"
    return
```

**Comment by bojidar-bg** [comment]
Well....
https://github.com/paulpflug/color-tabs/issues/11

**Comment by averrin** [comment]
Good for us=)
